### ISSUE TITLE
Can not access local variable 'read_mems_tmp' when using --use_NAM_seeds

### ISSUE THREAD

**Issue by FadelBerakdar** [ksahlin/ultra#19]
Hi, 

I am facing the following problem when running uLTRA with [GRCh38_p13_v43 ](https://www.gencodegenes.org/human/) and dataset [ENCLB632GYO](https://www.encodeproject.org/experiments/ENCSR016IKV/)

```
uLTRA align /mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/refs/GRCh38_p13_v43/genome.fa <(zcat /mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/reads/ENCLB632GYO_1k.fastq.gz)  /mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/aligned/ --index /mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/refs/GRCh38_p13_v43/uLTRA.idx --prefix uLTRA__GRCh38_p13_v43__ENCLB632GYO --use_NAM_seeds --min_mem 17 --min_acc 0.6 --disable_mm2 
<multiprocessing.context.SpawnContext object at 0x7fd92ba61e10>
Environment set: <multiprocessing.context.SpawnContext object at 0x7fd92ba61e10>
Using 3 cores.
Processing reads for MEM finding
Using StrobeMap
['StrobeMap', '-n', '2', '-k', '10', '-v', '11', '-w', '35', '-C', '500', '-L', '1000', '-S', '-t', '3', '-s', '-o', '/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/aligned/', '/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/aligned/refs_sequences.fa', '/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/aligned/reads_tmp.fq']
Time for StrobeMap to find NAMs:266.5836818218231 seconds.
Starting aligning reads.
Nr reads: 0 nr batches: 3 [0, 0, 0]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/lib/python3.11/site-packages/modules/align.py", line 670, in align_single_helper
    return align_single(*arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/lib/python3.11/site-packages/modules/align.py", line 434, in align_single
    for (read_acc, mems), (_, mems_rc) in zip(mem_wrapper.get_mem_records(mems_path,reads), mem_wrapper.get_mem_records(mems_path_rc, reads)):
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/lib/python3.11/site-packages/modules/mem_wrapper.py", line 151, in get_mem_records
    for chr_id in list(read_mems_tmp.keys()):
                       ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'read_mems_tmp' where it is not associated with a value
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/bin/uLTRA", line 717, in <module>
    align_reads(args)
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/bin/uLTRA", line 473, in align_reads
    classifications, alignment_outfiles = align.align_parallel(read_batches, refs_lengths, args)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/lib/python3.11/site-packages/modules/align.py", line 688, in align_parallel
    results =res.get(999999999) # Without the timeout this blocking call ignores all signals.
             ^^^^^^^^^^^^^^^^^^
  File "/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
UnboundLocalError: cannot access local variable 'read_mems_tmp' where it is not associated with a value
(/mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/.snakemake/conda/c61ef846c9b16f24a589aa5281ebe56c_) 
```

uLTRA runs perfectly when using the defaults parameters (using slamem instead of strobemap )
```
uLTRA align /mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/refs/GRCh38_p13_v43/genome.fa <(zcat /mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/reads/ENCLB632GYO_1k.fastq.gz)  /mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/aligned/ --index /mnt/storage3/users/ahberam1/DetectSpJunBenchmark/workflow/data/refs/GRCh38_p13_v43/uLTRA.idx --prefix uLTRA__GRCh38_p13_v43__ENCLB632GYO  --disable_mm2 

<multiprocessing.context.SpawnContext object at 0x7fe4942d2090>
Environment set: <multiprocessing.context.SpawnContext object at 0x7fe4942d2090>
Using 3 cores.
batch nt: 291444 total_nt: 874331
330
331
339
Using SLAMEM
Using SLAMEM
Using SLAMEM
Using SLAMEM
Using SLAMEM
Using SLAMEM
Time for slaMEM to find mems:3035.6001048088074 seconds.
Starting aligning reads.
Nr reads: 1000 nr batches: 3 [330, 331, 339]
READ 331 RECORDS.
READ 331 RECORDS.
READ 339 RECORDS.
READ 339 RECORDS.
Number of instances solved with quadratic collinear chainer solution: 395
Number of instances solved with n*log n collinear chainer solution: 164
Number of instances solved with quadratic collinear chainer solution: 445
Number of instances solved with n*log n collinear chainer solution: 217
READ 330 RECORDS.
READ 330 RECORDS.
Number of instances solved with quadratic collinear chainer solution: 375
Number of instances solved with n*log n collinear chainer solution: 239
Time elapesd multiprocessing: 1526.938672542572
Time to align reads:1526.9394431114197 seconds.
Time to merge SAM-files:0.029903173446655273 seconds.
defaultdict(<class 'int'>, {'FSM': 364, 'NIC_novel': 87, 'unaligned': 304, 'NO_SPLICE': 121, 'Insufficient_junction_coverage_unclassified': 95, 'ISM/NIC_known': 27, 'NNC': 2})
total alignment coverage: 567.6854821244016
Deleting temporary files...
```

conda enviroment:
```
name: env_ultra_exp
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - k8=0.2.5=hd03093a_2
  - ld_impl_linux-64=2.40=h41732ed_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.0=h417c0b6_0
  - minimap2=2.24=h7132678_1
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.0=h0b41bf4_0
  - pip=23.0.1=pyhd8ed1ab_0
  - python=3.11.1=h2755cc3_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=67.6.1=pyhd8ed1ab_0
  - slamem=0.8.5=hec16e2b_1
  - strobemap=0.0.2=hd03093a_1
  - tk=8.6.12=h27826a3_0
  - tzdata=2023c=h71feb2d_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - argcomplete==3.0.5
      - argh==0.28.1
      - dill==0.3.6
      - edlib==1.3.9
      - gffutils==0.11.1
      - intervaltree==3.1.0
      - numpy==1.24.2
      - parasail==1.3.4
      - pyfaidx==0.7.2.1
      - pysam==0.20.0
      - simplejson==3.18.4
      - six==1.16.0
      - sortedcontainers==2.4.0
      - ultra-bioinformatics==0.0.4.2
```

**Comment by ksahlin** [comment]
Hi @FadelBerakdar ,

First off, I will make it easy for me and say that the StrobeMap version (`--use_nams`) is experimental. 

However, I had a quick look at what you pasted and, from the command lines, it looks like you have only 900 reads calling it with slaMEM, and 0 reads(?!) in the `--use_nam` run. Have you verified the input read file is not empty or malformatted?

Maybe the `<(zcat  ...../ENCLB632GYO_1k.fastq.gz)` is causing some trouble not unpacking all the reads in time for mapping as you are streaming in the reads. I don't think the fastq parser can parse a stream or gzipped input unfortunately.

I had plans over the coming days revise a bit in the seed finding part of uLTRA (slaMEM/StrobeMap) at that time I can have a look into parsing gzipped formats as well.

**Comment by FadelBerakdar** [comment]
Hi @ksahlin 

Thank you for your reply, yes indeed the prolem was with the zcat command.
