### ISSUE TITLE
Bug with uLTRA align : TypeError: bad argument type for built-in operation

### ISSUE THREAD

**Issue by laetitiarialland** [ksahlin/ultra#21]
Hello, 

I try to align fastq data with uLTRA but it generates this error : 

Process Process-18:
Traceback (most recent call last):
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/site-packages/modules/align.py", line 484, in align_single
    read_seq, warning_log_file, min_acc)
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/site-packages/modules/classify_read_with_mams.py", line 426, in main
    choord_to_exon_id, segment_to_gene, gene_to_small_segments)
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/site-packages/modules/classify_read_with_mams.py", line 266, in get_unique_segment_and_flank_choordinates
    small_segments = set((small_chr_id, small_start,small_stop) for gene_id in unique_genes for (small_chr_id, small_start,small_stop) in grouper(gene_to_small_segments[gene_id], 3))
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/site-packages/modules/classify_read_with_mams.py", line 266, in <genexpr>
    small_segments = set((small_chr_id, small_start,small_stop) for gene_id in unique_genes for (small_chr_id, small_start,small_stop) in grouper(gene_to_small_segments[gene_id], 3))
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.6/site-packages/modules/create_augmented_gene.py", line 69, in <lambda>
    gene_to_small_segments = defaultdict(lambda :array("L")) #defaultdict(lambda :array("b"))
TypeError: bad argument type for built-in operation
Process Process-25:
Traceback (most recent call last):
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/site-packages/modules/align.py", line 484, in align_single
    read_seq, warning_log_file, min_acc)
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/site-packages/modules/classify_read_with_mams.py", line 426, in main
    choord_to_exon_id, segment_to_gene, gene_to_small_segments)
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/site-packages/modules/classify_read_with_mams.py", line 266, in get_unique_segment_and_flank_choordinates
    small_segments = set((small_chr_id, small_start,small_stop) for gene_id in unique_genes for (small_chr_id, small_start,small_stop) in grouper(gene_to_small_segments[gene_id], 3))
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.5/site-packages/modules/classify_read_with_mams.py", line 266, in <genexpr>
    small_segments = set((small_chr_id, small_start,small_stop) for gene_id in unique_genes for (small_chr_id, small_start,small_stop) in grouper(gene_to_small_segments[gene_id], 3))
  File "/home/rialland/anaconda3/envs/ULTRA/lib/python3.6/site-packages/modules/create_augmented_gene.py", line 69, in <lambda>
    gene_to_small_segments = defaultdict(lambda :array("L")) #defaultdict(lambda :array("b"))
TypeError: bad argument type for built-in operation

I'm not very familiar with python so I do not find what's going on... I've ran this command : uLTRA align GRCh38.p13bgz.fa FT_PIL005_1.fastq.gz /scratchbeta/rialland/LONGREAD/ --index /scratchbeta/rialland/LONGREAD/GRCh38p13  --ont --t 24  > u_5_1.sam
I'm working with uLTRA v0.1 and python 3.5

How can I fix it ? 

Thanks, 

Kind regards, 

Laëtitia RIALLAND

**Comment by ksahlin** [comment]
Hi @laetitiarialland , 

I had a look and while I am not sure (I have never seen this error),  one suspicious thing I note is in your error message is that you first have a lot of lines with
`home/rialland/anaconda3/envs/ULTRA/lib/python3.5/` then comes `/home/rialland/anaconda3/envs/ULTRA/lib/python3.6`

i.e. using both python 3.5 and 3.6. You likely have a python version conflict - and since that is the only suspicious thing I see here, I am going to guess that could be responsible for the error.

So I would try to take care of that. By uninstalling and reinstalling uLTRA in a clean python environment.

**Comment by sguizard** [comment]
Or you cqn try to use the bioconda package. It should resolve any version conflict.

**Comment by laetitiarialland** [comment]
Thanks for your help !! 
Effectively, I reinstall ultra with a clean version of python and it works !! 

Thank you a lot, 

Kind regards, 
Laëtitia RIALLAND
