### ISSUE TITLE
Ultra index failed

### ISSUE THREAD

**Issue by Yangliu9ReviR** [ksahlin/ultra#26]
I'm running ultra index using hg38 and gencode gtf, 

`uLTRA index GRCh38.primary_assembly.genome.fa gencode.v41.annotation.gtf ultra_index --disable_infer`

and it gives the following error

`Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/ultra/bin/uLTRA", line 555, in <module>
    prep_splicing(args, refs_lengths)
  File "/home/ubuntu/miniconda3/envs/ultra/bin/uLTRA", line 81, in prep_splicing
    max_intron_chr, exon_choordinates_to_id, chr_to_id, id_to_chr = augmented_gene.create_graph_from_exon_parts(db, args.flank_size, args.small_exon_threshold, args.min_segm, refs_lengths)
  File "/home/ubuntu/miniconda3/envs/ultra/lib/python3.8/site-packages/modules/create_augmented_gene.py", line 440, in create_graph_from_exon_parts
    assert active_start <= exon.start - 1
AssertionError`

And I also tested the index using test data provided in the repo and encountered the same issue.

Any ideas?

**Comment by Yangliu9ReviR** [comment]
I'll close the issue because it's discussed previously
